apiVersion: v1
kind: Pod
metadata:
  name: nginx-sample-pod-2
  labels:
    app: nginx-app
spec:
  volumes:
  - name: nginx-storage
    emptyDir: {}
  containers:
  - name: nginx-container
    image: nginx:latest
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: nginx-storage
    ports:
    - containerPort: 80
