apiVersion: v1
kind: Service
metadata:
  name: lb-service
spec:
  type: LoadBalancer
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80 # The port that the service will listen on
      targetPort: 8080 # The port on the pods that the service will forward to

# This service will create a LoadBalancer that listens on port 80 and forwards traffic to pods with the label "app: my-app" on port 8080.
# Kubernetes actually creates:
# A ClusterIP
# A NodePort
# Then attaches an external load balancer (in cloud)

# # kubectl get svc lb-service
# NAME         TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)
# lb-service   LoadBalancer   10.96.12.34     <pending>     80:31245/TCP

# Here 
# | Component               | Port  |
# | ----------------------- | ----- |
# | ClusterIP               | 80    |
# | NodePort (auto created) | 31245 |
# | External LoadBalancer   | 80    |

