apiVersion: v1
kind: Service
metadata:
  name: my-nodeport-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80 # Service Port
      targetPort: 80 # Container Port
      nodePort: 30007 # Node Port
  type: NodePort
# Here we have specified type as NodePort to expose the service on a static port on each Node's IP